name: pupsy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  cloud_firestore: ^4.15.8
  cloud_functions: ^4.6.8
  firebase_storage: ^11.6.9
  firebase_database_web: ^0.2.1+9
  carousel_slider: ^4.0.0
  change_app_package_name: ^1.1.0
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/
